#pragma once

#if FRAMEWORK_RUNTIME_MODE_CURRENT == FRAMEWORK_RUNTIME_MODE_FLASH_MGR
#define FLASH_MGR_ENABLE 1
#else
#define FLASH_MGR_ENABLE 0
#endif

#if FRAMEWORK_RUNTIME_MODE_CURRENT == FRAMEWORK_RUNTIME_MODE_GAME
#define GAME_CONSOLE_ENABLE 1
#else
#define GAME_CONSOLE_ENABLE 0
#endif

#define GAME_RUNTIME_MONITOR_ENABLE      0
#define GAME_RUNTIME_MONITOR_INTERVAL_MS 5000u
