build:
  build_type: MinSizeRel          # Debug | Release | RelWithDebInfo | MinSizeRel
  generator: ninja             # ninja | make | auto
  graphviz: ON                 # ON | OFF — appends --graphviz=framework.dot

  FRAMEWORK_USE_FREERTOS: ON
  FRAMEWORK_USE_RTT: ON
  FRAMEWORK_USE_LVGL: OFF
  FRAMEWORK_USE_LFS: ON
