build:
  # - name: vm
  #   platform: VM
  #   build_type: Release
  #   generator: ninja
  #   graphviz: ON

  #   FRAMEWORK_USE_FREERTOS: ON
  #   FRAMEWORK_USE_RTT: OFF
  #   FRAMEWORK_USE_LVGL: OFF
  #   FRAMEWORK_USE_LFS: ON
  #   FRAMEWORK_USE_UART: OFF

  - name: arm
    platform: ARM
    build_type: MinSizeRel # Debug | Release | RelWithDebInfo | MinSizeRel
    generator: ninja       # ninja | make | auto
    graphviz: ON           # ON | OFF

    FRAMEWORK_USE_FREERTOS: ON
    FRAMEWORK_USE_RTT: OFF
    FRAMEWORK_USE_LVGL: OFF
    FRAMEWORK_USE_LFS: ON
    FRAMEWORK_USE_UART: OFF
