#!/usr/bin/env python3
"""Convert airplane battle artwork into compact firmware-side RGB565 assets."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / "assets" / "images"
OUTPUT_DIR = ROOT / "src" / "app" / "air_battle"


@dataclass(frozen=True)
class Sprite:
    symbol: str
    filename: str
    size: tuple[int, int]


SPRITES = (
    Sprite("air_sprite_hero", "hero.png", (36, 30)),
    Sprite("air_sprite_mob", "mob.png", (26, 18)),
    Sprite("air_sprite_elite", "elite.png", (34, 22)),
    Sprite("air_sprite_elite_pro", "elitePro.png", (34, 28)),
    Sprite("air_sprite_boss", "boss.png", (64, 43)),
    Sprite("air_sprite_bullet_hero", "bullet_hero.png", (4, 10)),
    Sprite("air_sprite_bullet_enemy", "bullet_enemy.png", (4, 8)),
    Sprite("air_sprite_prop_blood", "prop_blood.png", (14, 13)),
    Sprite("air_sprite_prop_bomb", "prop_bomb.png", (14, 14)),
    Sprite("air_sprite_prop_bullet", "prop_bulletPlus.png", (14, 14)),
)


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)


def format_array(values: list[int], width: int, suffix: str = "u") -> str:
    lines = []
    for start in range(0, len(values), width):
        row = values[start : start + width]
        lines.append("    " + ", ".join(f"0x{value:04x}{suffix}" for value in row) + ",")
    return "\n".join(lines)


def format_bytes(values: list[int], width: int = 16) -> str:
    lines = []
    for start in range(0, len(values), width):
        row = values[start : start + width]
        lines.append("    " + ", ".join(f"0x{value:02x}u" for value in row) + ",")
    return "\n".join(lines)


def load_sprite(sprite: Sprite) -> tuple[list[int], list[int]]:
    image = Image.open(SOURCE_DIR / sprite.filename).convert("RGBA")
    image.thumbnail(sprite.size, Image.Resampling.LANCZOS)
    canvas = Image.new("RGBA", sprite.size, (0, 0, 0, 0))
    x = (sprite.size[0] - image.width) // 2
    y = (sprite.size[1] - image.height) // 2
    canvas.alpha_composite(image, (x, y))

    pixels: list[int] = []
    mask: list[int] = []
    mask_byte = 0
    mask_bits = 0
    edge_background = (9, 27, 54)

    for red, green, blue, alpha in canvas.getdata():
        blend = alpha / 255.0
        red = round(red * blend + edge_background[0] * (1.0 - blend))
        green = round(green * blend + edge_background[1] * (1.0 - blend))
        blue = round(blue * blend + edge_background[2] * (1.0 - blend))
        pixels.append(rgb565(red, green, blue))

        if alpha >= 40:
            mask_byte |= 1 << mask_bits
        mask_bits += 1
        if mask_bits == 8:
            mask.append(mask_byte)
            mask_byte = 0
            mask_bits = 0

    if mask_bits:
        mask.append(mask_byte)
    return pixels, mask


def generate() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    background = Image.open(SOURCE_DIR / "bg2.jpg").convert("RGB")
    background = ImageOps.fit(
        background, (80, 107), method=Image.Resampling.LANCZOS, centering=(0.5, 0.5)
    )
    background_pixels = [rgb565(*pixel) for pixel in background.getdata()]

    header = """#pragma once

#include <stdint.h>

#define AIR_BACKGROUND_WIDTH  80
#define AIR_BACKGROUND_HEIGHT 107
#define AIR_BACKGROUND_SCALE  3

typedef struct {
    uint8_t width;
    uint8_t height;
    const uint16_t* pixels;
    const uint8_t* mask;
} Air_sprite;

extern const uint16_t air_background[AIR_BACKGROUND_WIDTH * AIR_BACKGROUND_HEIGHT];
"""
    for sprite in SPRITES:
        header += f"extern const Air_sprite {sprite.symbol};\n"

    source = """#include "air_assets.h"

/* Generated by scripts/generate_air_battle_assets.py. */
const uint16_t air_background[AIR_BACKGROUND_WIDTH * AIR_BACKGROUND_HEIGHT] = {
"""
    source += format_array(background_pixels, 10)
    source += "\n};\n\n"

    for sprite in SPRITES:
        pixels, mask = load_sprite(sprite)
        source += (
            f"static const uint16_t {sprite.symbol}_pixels"
            f"[{sprite.size[0] * sprite.size[1]}] = {{\n"
        )
        source += format_array(pixels, 10)
        source += "\n};\n"
        source += f"static const uint8_t {sprite.symbol}_mask[{len(mask)}] = {{\n"
        source += format_bytes(mask)
        source += "\n};\n"
        source += (
            f"const Air_sprite {sprite.symbol} = "
            f"{{{sprite.size[0]}u, {sprite.size[1]}u, "
            f"{sprite.symbol}_pixels, {sprite.symbol}_mask}};\n\n"
        )

    (OUTPUT_DIR / "air_assets.h").write_text(header.rstrip() + "\n", encoding="ascii")
    (OUTPUT_DIR / "air_assets.c").write_text(source.rstrip() + "\n", encoding="ascii")


if __name__ == "__main__":
    generate()
