#!/usr/bin/env python3
"""
Encode Bad Apple!! frames as 1-bit delta video for ST7789 LCD.

Each pixel is thresholded to black (0) or white (1), and segment pixel
data is packed 8 pixels per byte for ~4× storage reduction vs 8-bit.

Usage:
    python tools/encode_badapple.py                         \
        --input   img/BadApple                               \
        --output  src/hal/lcd/lcd_video_delta_data.h          \
        --name    g_badapple_delta                            \
        --start-frame 7        --max-frames 20                \
        --fps 4
"""

import argparse
import os
import sys
from PIL import Image


# ═══════════════════════════════════════════════════════════════════
#  1‑bit delta encoding
# ═══════════════════════════════════════════════════════════════════

def threshold1(px) -> list:
    """Convert an (R,G,B) pixel list to a 1‑bit list {0, 1}."""
    return [0 if (r + g + b) // 3 < 128 else 1 for (r, g, b) in px]


def compute_row_segments_1bit(prev_row, curr_row):
    """
    Yield (col_start, col_end, bits) for contiguous runs of changed
    pixels within one 1‑bit row.  `bits` is a list of ints {0,1}.
    """
    i = 0
    w = len(prev_row)
    while i < w:
        if prev_row[i] == curr_row[i]:
            i += 1
            continue
        col_start = i
        seg = []
        while i < w and prev_row[i] != curr_row[i]:
            seg.append(curr_row[i])
            i += 1
        yield col_start, col_start + len(seg) - 1, seg


def pack_bits(bits: list) -> bytes:
    """Pack a list of {0,1} ints MSB‑first, 8 per byte."""
    buf = bytearray()
    for i in range(0, len(bits), 8):
        byte = 0
        for j in range(8):
            if i + j < len(bits):
                byte |= bits[i + j] << (7 - j)
        buf.append(byte)
    return bytes(buf)


def encode_delta_frame_1bit(prev_frame_1b, curr_frame_1b, height=240):
    """
    Encode one delta frame as a bytearray with packed 1‑bit pixels.

    Layout:
      [0..1]   uint16 LE  packed_bytes   (packed pixel data only)
      [2..3]   uint16 LE  num_segments
      [... segments ...]
      Each segment:
        [0]              uint8  row
        [1]              uint8  col_start
        [2]              uint8  col_end
        [3..]            uint8  packed_bits[ceil((col_end-col_start+1)/8)]
    """
    segments = []
    for row in range(height):
        for cs, ce, bits in compute_row_segments_1bit(prev_frame_1b[row],
                                                       curr_frame_1b[row]):
            segments.append((row, cs, ce, pack_bits(bits)))

    buf = bytearray()
    packed_bytes = sum(len(s[3]) for s in segments)
    buf += packed_bytes.to_bytes(2, 'little')
    buf += len(segments).to_bytes(2, 'little')

    for row, cs, ce, pk in segments:
        buf.append(row)
        buf.append(cs)
        buf.append(ce)
        buf.extend(pk)

    return bytes(buf), packed_bytes


# ═══════════════════════════════════════════════════════════════════
#  C header generation
# ═══════════════════════════════════════════════════════════════════

def render_c_header(frame_index, raw_blob, array_name, fps):
    lines = []
    lines.append("// Auto-generated by tools/encode_badapple.py  --  DO NOT EDIT")
    lines.append(f"// Frames: {len(frame_index)}  @ {fps} fps  (1-bit)")
    lines.append(f"// Total delta bytes: {len(raw_blob)}")
    lines.append("#pragma once")
    lines.append("#include \"lcd_video_player.h\"")
    lines.append("")
    lines.append(f"#define LCD_VIDEO_FRAME_COUNT  {len(frame_index)}U")
    lines.append(f"#define LCD_VIDEO_FPS           {fps}U")
    lines.append("")

    data_name = f"{array_name}_data"
    lines.append(f"// ── Delta data blob ({len(raw_blob)} bytes) ──")
    lines.append(f"static const uint8_t {data_name}[] = {{")
    for i in range(0, len(raw_blob), 16):
        chunk = raw_blob[i:i+16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {hex_str},")
    lines.append("};")
    lines.append("")

    idx_name = f"{array_name}_frames"
    lines.append(f"// ── Frame index table ({len(frame_index)} entries) ──")
    lines.append(f"static const LcdDeltaFrame {idx_name}[] = {{")
    for off, pb, sc in frame_index:
        lines.append(f"    {{.offset = {off}U, .packed_bytes = {pb}, .num_segments = {sc}}},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════
#  Main
# ═══════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description="Encode 1-bit delta video for ST7789")
    parser.add_argument("--input", default="img/BadApple")
    parser.add_argument("--output", default="src/hal/lcd/lcd_video_delta_data.h")
    parser.add_argument("--name", default="g_badapple_delta")
    parser.add_argument("--start-frame", type=int, default=1)
    parser.add_argument("--max-frames", type=int, default=120)
    parser.add_argument("--fps", type=int, default=4)
    args = parser.parse_args()

    all_frames = sorted([
        os.path.join(args.input, f)
        for f in os.listdir(args.input)
        if f.startswith("frame_") and f.endswith(".png")
    ])
    start_idx = max(0, args.start_frame - 1)
    end_idx = min(len(all_frames), start_idx + args.max_frames)
    frame_paths = all_frames[start_idx:end_idx]

    if not frame_paths:
        print("No frames in range!", file=sys.stderr)
        sys.exit(1)

    print(f"Encoding 1-bit: frames {args.start_frame}..{args.start_frame + len(frame_paths) - 1}"
          f"  ({len(frame_paths)} frames)")

    H, W = 240, 240
    prev_1b = [[0] * W for _ in range(H)]  # all-black baseline

    raw_blob = bytearray()
    frame_index = []

    for idx, fpath in enumerate(frame_paths, start=args.start_frame):
        img = Image.open(fpath).convert("RGB")
        px = list(img.getdata())
        b1 = threshold1(px)
        curr_1b = [[b1[y * W + x] for x in range(W)] for y in range(H)]

        delta_bytes, packed_bytes = encode_delta_frame_1bit(prev_1b, curr_1b, H)
        seg_count = int.from_bytes(delta_bytes[2:4], 'little')
        frame_index.append((len(raw_blob), packed_bytes, seg_count))
        raw_blob.extend(delta_bytes)

        # count actual changed 1-bit pixels
        changed = sum(1 for a, b in zip(
            [px for row in prev_1b for px in row],
            [px for row in curr_1b for px in row]) if a != b)
        pct = changed * 100 / (W * H)
        print(f"  Frame {idx:3d}: {changed:5d} pix ({pct:5.1f}%)  segs={seg_count:4d}  "
              f"packed={packed_bytes:5d}B  delta={len(delta_bytes):5d}B")

        prev_1b = curr_1b

    total_pixel_changes = sum(
        sum(1 for a, b in zip(
            [0]*W*H if i == 0 else [],  # skip, we track differently
            []))
        for i in range(len(frame_paths)))
    actual = len(raw_blob)
    avg = actual / len(frame_paths) if frame_paths else 0

    print(f"\n{'='*60}")
    print(f"Total delta blob:  {actual} bytes ({actual/1024:.1f} KB)")
    print(f"Avg per frame:     {avg:.0f} bytes")
    print(f"Est. SPI fps:      {400000/avg:.1f}  (@ 400KB/s)")
    print(f"Fits in 128KB:     {'YES' if actual + 22000 < 128*1024 else 'NO'}")

    header = render_c_header(frame_index, raw_blob, args.name, args.fps)
    out_path = os.path.normpath(os.path.join(
        os.path.dirname(__file__) or ".", "..", args.output))
    with open(out_path, "w") as f:
        f.write(header)
    print(f"\nWritten: {out_path}")


if __name__ == "__main__":
    main()
