if(WIN32)
    set(ColorReset "")
    set(ColorBold "")
    set(ColorRed "")
    set(ColorGreen "")
    set(ColorYellow "")
    set(ColorBlue "")
    set(ColorMagenta "")
    set(ColorCyan "")
    set(ColorWhite "")
    set(ColorBoldRed "")
    set(ColorBoldGreen "")
    set(ColorBoldYellow "")
    set(ColorBoldBlue "")
    set(ColorBoldMagenta "")
    set(ColorBoldCyan "")
    set(ColorBoldWhite "")
else()
    string(ASCII 27 Esc)
    set(ColorReset "${Esc}[m")
    set(ColorBold "${Esc}[1m")
    set(ColorRed "${Esc}[31m")
    set(ColorGreen "${Esc}[32m")
    set(ColorYellow "${Esc}[33m")
    set(ColorBlue "${Esc}[34m")
    set(ColorMagenta "${Esc}[35m")
    set(ColorCyan "${Esc}[36m")
    set(ColorWhite "${Esc}[37m")
    set(ColorBoldRed "${Esc}[1;31m")
    set(ColorBoldGreen "${Esc}[1;32m")
    set(ColorBoldYellow "${Esc}[1;33m")
    set(ColorBoldBlue "${Esc}[1;34m")
    set(ColorBoldMagenta "${Esc}[1;35m")
    set(ColorBoldCyan "${Esc}[1;36m")
    set(ColorBoldWhite "${Esc}[1;37m")
endif()

macro(print_blankline)
    message("")
endmacro()

macro(print_status msg)
    message(STATUS "${ColorBlue}[INFO]${ColorReset} ${msg}")
endmacro()

macro(print_success msg)
    message(STATUS "${ColorGreen}[SUCCESS]${ColorReset} ${msg}")
endmacro()

macro(print_warning msg)
    message(WARNING "${ColorYellow}[WARNING]${ColorReset} ${msg}")
endmacro()

macro(print_error msg)
    message(FATAL_ERROR "${ColorRed}[ERROR]${ColorReset} ${msg}")
endmacro()

macro(print_item tag msg)
    message(STATUS "${ColorBlue}[${tag}]${ColorReset} ${msg}")
endmacro()

function(get_subdirs base_dir out_list)
    file(GLOB SUBDIRS_LIST "${base_dir}/*")
    
    set(RESULT "")
    foreach(ITEM ${SUBDIRS_LIST})
        if(IS_DIRECTORY ${ITEM})
            list(APPEND RESULT ${ITEM})
        endif()
    endforeach()

    set(${out_list} ${RESULT} PARENT_SCOPE)
endfunction()

function(get_subdirs_and_self base_dir out_list)
    get_subdirs(${base_dir} ${out_list})
    list(APPEND ${out_list} ${base_dir})
    set(${out_list} ${${out_list}} PARENT_SCOPE)
endfunction()
